// ============================================================================
// القاموس الشامل (يحتوي على نصوص النظام بالكامل)
// ============================================================================
export const translations = {
    en: {
        // --- Shared & General ---
        langBtn: "العربية",
        logo: "EnQaZ",
        loading: "Loading...",
        processing: "Processing...",
        save: "Save",
        cancel: "Cancel",
        close: "Close",
        delete: "Delete",
        edit: "Edit",
        view: "View",
        status: "Status",
        actions: "Actions",

        navHome: "Home",
        navApply: "Apply for Device",
        navTrack: "Track Patient",
        navHow: "How it Works",
        navLogin: "Login Portal",
        
        liveBadge: "Intelligent Ambulance Dispatch Active",
        mainHeroTitle: "Every Second <br> <span class=\"text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-primary\">Counts.</span>",
        mainHeroDesc: "ResQ platform automates accident detection, instantly verifying incidents and dispatching the nearest ambulance.",
        btnTrack: "Track Patient Status",
        
        simTitle: "Live Coordination Map",
        
        searchTitle: "Track Patient Status",
        searchDesc: "Enter the unique Device UID to check the real-time status and destination hospital of the patient.",
        deviceUid: "Device UID",
        btnSearch: "Search Database",
        
        howTitle: "System Protocol",
        step1Title: "Hardware Detection",
        step1Desc: "G-Force sensors detect impact instantly and send coords.",
        step2Title: "10-Sec Verification",
        step3Title: "Auto-Dispatch",
        step4Title: "Hospital Alert",
        // --- Admin Global UI ---
        desktopOnly: "Desktop & Tablet Only",
        desktopOnlyDesc: "Command Center requires a larger screen for real-time map telemetry.",
        returnHome: "Return to Home",
        adminTitle: "EnQaZ Admin",
        aiDispatch: "AI Dispatch Live",
        maximizeMap: "Maximize Map",
        showPanels: "Show Panels",
        
        // --- Sidebar ---
        navDash: "Dashboard",
        navUsers: "Users",
        navHospitals: "Hospitals",
        navAmbulances: "Ambulances",

        // --- Dashboard Module ---
        dashIncidents: "Incidents",
        dashFleet: "Fleet",
        dashDevices: "Active Devices",
        searchDevicePlaceholder: "Search ID or Owner...",
        panelDetailsTitle: "Details",

        // --- Users Module ---
        usersTitle: "Users Management",
        usersDesc: "Manage drivers, hospitals, admins, and app users.",
        addNewUser: "Add New User",
        searchUsers: "Search Name, Email, ID...",
        allRoles: "All Roles",
        allStatus: "All Status",
        active: "Active",
        suspended: "Suspended",
        id: "ID",
        name: "Name",
        email: "Email",
        phone: "Phone",
        role: "Role",

        // --- Hospitals Module ---
        hospTitle: "Hospitals Network",
        hospDesc: "Manage facilities, locations, and real-time bed capacities.",
        addHosp: "Add Hospital",
        searchHosp: "Search Name, City, ID...",
        allCapacities: "All Capacities",
        bedsAvailable: "Beds Available",
        fullBeds: "Full (0 Beds)",
        hospName: "Hospital Name",
        location: "Location",
        availBeds: "Available Beds",
        adminAcc: "Admin Account",
// --- Devices Module ---
        navDevices: "Devices",
        devTitle: "Devices Management",
        devDesc: "Manage hardware crash-detection units, assign owners, and track status.",
        addDevice: "Add Device",
        searchDevice: "Search UID, Owner, Car Plate...",
        colDeviceUid: "Device UID",
        colOwner: "Owner Info",
        colCarInfo: "Car Details",
        modalAddDevTitle: "Add New Device",
        lblDeviceUid: "Hardware UID (Unique)",
        lblAssignUser: "Assign to User",
        lblCarModel: "Car Model & Year",
        lblCarPlate: "License Plate",
        btnSaveDevice: "Save Device",
        modalViewDevTitle: "Device Profile",
        lblRegDate: "Registration Date",
        modalDevFilterTitle: "Geographic Devices Filter",
        lblFilterDescDev: "Click on the map to set a center point, then adjust the radius to find active devices within that zone.",
        unassigned: "Unassigned",
        confirmTitle: "Are you sure?",
        confirmMessage: "This action cannot be undone.",
        btnTraffic: "Live Traffic",
        btnHeatmap: "Incident Heatmap",
        notifications: "Notifications",
        noNotifs: "No new notifications",
        logout: "Logout",
        // --- Ambulances Module ---
        ambTitle: "Fleet Management",
        ambDesc: "Manage ambulance units, drivers, and dispatch base zones.",
        addAmb: "Add Unit",
        searchAmb: "Search Code, Driver...",
        mapFilter: "Map Filter",
        unitCode: "Unit Code",
        assignedDriver: "Assigned Driver",
        baseZone: "Base Zone",
        // --- Logs Module ---
        navLogs: "System Logs",
        logsTitle: "Audit & Activity Logs",
        logsDesc: "Track all administrative actions, updates, and deletions.",
        searchLogs: "Search admin name, notes...",
        allActions: "All Actions",
        allTables: "All Modules",
        colDate: "Date & Time",
        colAdmin: "Admin",
        colAction: "Action",
        colTarget: "Target Module",
        colNote: "Details / Note",
        // --- Incidents Module ---
        navIncidents: "Incident Records",
        incRecordsTitle: "Emergency Incident Logs",
        incRecordsDesc: "Review historic incidents, impact data, and response times.",
        searchInc: "Search Incident ID, Device UID...",
        colGForce: "G-Force",
        colResponse: "Response Status",
        modalViewIncTitle: "Incident Report",
        lblIncidentTime: "Incident Time",
        lblResolvedTime: "Resolved At",
        lblAssignedAmb: "Assigned Ambulance",
        lblAssignedHosp: "Assigned Hospital",
        modalIncFilterTitle: "Geographic Incident Search",
        lblFilterDescInc: "Locate incidents within a specific radius on the map.",

        speed: "Speed at Impact",
        timeline: "Incident Lifecycle Timeline",
        outcome: "Medical Outcome",
        treated: "Discharged / Treated",
        deceased: "Deceased",
        impactPoint: "Impact Location",
        stepCreated: "Collision Detected",
        stepAssigned: "Ambulance Dispatched",
        stepArrived: "Ambulance Reached Site",
        stepHospital: "Arrived at Hospital",
        stepResolved: "Medical Case Closed",
        sysInit: "System Initialized. Scanning area...",
crashDetected: "CRASH DETECTED: Civilian Vehicle #",
dispatching: "Dispatching",
toCrashSite: "to crash site...",
securingPatient: "securing patient...",
routingTo: "routing to",
droppedPatient: "dropped patient. Resuming patrol.",
wfComplete: "PROTOCOL COMPLETE. RESTARTING...",
wfImpact: "IMPACT DETECTED. CAPTURING TELEMETRY...",
wfUplink: "UPLINK ESTABLISHED. VERIFYING SIGNAL...",
wfAnalysing: "ANALYSING GPS MATRIX. DISPATCHING UNIT...",
wfHospital: "HOSPITAL HANDSHAKE SUCCESSFUL. PREPARING ER.",
navApps: "Device Applications",
appTitle: "Hardware Requests",
appTableOwner: "Applicant Name",
appTableCar: "Vehicle Info",
appStatus: "Status",
sysInit: "System Initialized. Scanning area...",
        crashDetected: "CRASH DETECTED: Civilian Vehicle #",
        dispatching: "Dispatching",
        toCrashSite: "to crash site...",
        securingPatient: "securing patient...",
        routingTo: "routing to",
        droppedPatient: "dropped patient. Resuming patrol.",
        wfComplete: "PROTOCOL COMPLETE. RESTARTING...",
        wfImpact: "IMPACT DETECTED. CAPTURING TELEMETRY...",
        wfUplink: "UPLINK ESTABLISHED. VERIFYING SIGNAL...",
        wfAnalysing: "ANALYSING GPS MATRIX. DISPATCHING UNIT...",
        wfHospital: "HOSPITAL HANDSHAKE SUCCESSFUL. PREPARING ER.",
driver_dashboard: "Ambulance Dashboard",
sim_mode: "Simulation Mode",
actual_mode: "Live Mode",
status_available: "Available",
status_offline: "Offline",
waiting_missions: "Waiting for new emergencies...",
patient_info: "Patient Information",
target_hospital: "Target Hospital",
confirm_arrival: "Confirm Arrival at Location",
confirm_delivery: "Confirm Hospital Delivery",
blood_type: "Blood Type",
medical_notes: "Medical Notes",
impact_force: "Impact Force",
vehicle_speed: "Vehicle Speed",
car_info: "Vehicle Info",
waiting: "Waiting for Dispatch...",
        standby: "You are on standby. You will be routed immediately upon emergency.",
        incDetails: "Emergency Incident Details",
        incNum: "Incident #:",
        patientData: "Patient Data",
        name: "Name",
        bloodType: "Blood Type",
        phone: "Phone",
        notes: "Medical Notes",
        hospital: "Destination (Hospital)",
        confirmRec: "Acknowledge Incident & Move",
        arrivedLoc: "Confirm Patient Pickup (Move to Hospital)",
        enRouteHosp: "En Route to Hospital...",
        arrivedHosp: "Confirm Arrival at Hospital",
        waitingHosp: "Waiting for Hospital to confirm handover...",
        driverUnknown: "Unknown Driver",
        noAmb: "No ambulance linked to your account.",
        unknown: "Unknown",
        determining: "Determining...",
        confirmed: "Confirmed",
        ackMsg: "Alarm stopped. Follow route to incident.",
        pickedUp: "Patient Picked Up",
        hospMsg: "Proceed to the hospital. Route updated.",
        smartNav: "Smart Navigation",
        navMsg: "Auto-rotation enabled.",
        error: "Error",
        newIncident: "🚨 New Dispatch!",
        newIncidentMsg: "A new incident has been assigned to you. Acknowledge immediately.",
        missionSuccess: "✅ Mission Accomplished",
        missionSuccessMsg: "Hospital has confirmed patient handover. You are now available.",
        statusUpdateError: "Failed to update status",
        alert: "Alert",

        // --- User Dashboard ---
        userDashTitle: "Patient Portal | EnQaZ",
        userGreeting: "Welcome",
        tabIncidents: "Incident History",
        tabVisitors: "Visitor Logs",
        tabSettings: "Settings",
        incHistoryTitle: "Incident History",
        incSearchPh: "Search by incident ID...",
        filterAll: "All",
        visitorLogsTitle: "Who Searched for You",
        visSearchPh: "Search by email...",
        visEmail: "Searcher Email",
        visMethod: "Search Method",
        visQuery: "Search Term",
        noVisitors: "No search records found",
        settingsTitle: "Personal Settings",
        personalInfo: "Personal Information",
        medicalInfo: "Medical Information",
        allergies: "Allergies",
        medications: "Medications",
        chronicConditions: "Chronic Conditions",
        emergencyContacts: "Emergency Contacts",
        ec1Name: "Contact 1 Name",
        ec1Phone: "Contact 1 Phone",
        ec1Relation: "Relation",
        changePassword: "Change Password",
        updatePassword: "Update",
        saveAll: "Save All Changes",
        incReportTitle: "Incident Report",
    },
    ar: {
        waiting: "في انتظار البلاغات...",
        standby: "أنت في وضع الاستعداد. سيتم توجيهك فور حدوث أي طارئ.",
        incDetails: "تفاصيل البلاغ الطارئ",
        incNum: "رقم البلاغ:",
        patientData: "بيانات المصاب",
        name: "الاسم",
        bloodType: "فصيلة الدم",
        phone: "الهاتف",
        notes: "ملاحظات طبية",
        hospital: "الوجهة (المستشفى)",
        confirmRec: "تأكيد استلام البلاغ والتحرك",
        arrivedLoc: "تأكيد استلام المصاب (التحرك للمستشفى)",
        enRouteHosp: "جاري النقل للمستشفى...",
        arrivedHosp: "تأكيد الوصول لساحة المستشفى",
        waitingHosp: "في انتظار تأكيد المستشفى لاستلام الحالة...",
        driverUnknown: "سائق غير معروف",
        noAmb: "لم يتم العثور على سيارة إسعاف مرتبطة بحسابك.",
        unknown: "مجهول",
        determining: "جاري التحديد...",
        confirmed: "تم التأكيد",
        ackMsg: "تم إيقاف الإنذار. اتبع المسار للوصول لموقع الحادث.",
        pickedUp: "تم استلام الحالة",
        hospMsg: "تحرك الآن باتجاه المستشفى، تم تحديث المسار.",
        smartNav: "الملاحة الذكية",
        navMsg: "تم تفعيل التوجيه التلقائي مع مسار الإسعاف.",
        error: "خطأ",
        newIncident: "🚨 بلاغ جديد!",
        newIncidentMsg: "تم توجيه حادث جديد إليك، يرجى التأكيد فوراً.",
        missionSuccess: "✅ تمت العملية",
        missionSuccessMsg: "قامت المستشفى بتأكيد استلام المريض. أنت الآن متاح للعمل.",
        statusUpdateError: "حدث خطأ أثناء تحديث الحالة",
        alert: "تنبيه",
        // --- Shared & General ---
        langBtn: "English",
        logo: "ريسكيو",
        loading: "جاري التحميل...",
        processing: "جاري المعالجة...",
        save: "حفظ",
        cancel: "إلغاء",
        close: "إغلاق",
        delete: "حذف",
        edit: "تعديل",
        view: "عرض",
        status: "الحالة",
        actions: "الإجراءات",
        logo: "إنقاذ",
        navHome: "الرئيسية",
        navApply: "طلب جهاز",
        navTrack: "تتبع مريض",
        navHow: "كيف يعمل النظام",
        navLogin: "بوابة الدخول",
        navApps: "طلبات الأجهزة",
appTitle: "سجل طلبات الأجهزة",
appTableOwner: "اسم المتقدم",
appTableCar: "بيانات المركبة",
appStatus: "الحالة",
sysInit: "تم تشغيل النظام. جاري فحص المنطقة...",
        crashDetected: "تم رصد حادث: سيارة مدنية رقم ",
        dispatching: "جاري توجيه",
        toCrashSite: "إلى موقع الحادث...",
        securingPatient: "يقوم بتأمين المصاب...",
        routingTo: "في طريقه إلى مستشفى",
        droppedPatient: "تم تسليم الحالة. العودة للدورية.",
        wfComplete: "اكتمل البروتوكول. جاري إعادة التشغيل...",
        wfImpact: "تم اكتشاف اصطدام. جاري جمع البيانات...",
        wfUplink: "تم الاتصال بالشبكة. جاري التحقق من الإشارة...",
        wfAnalysing: "جاري تحليل إحداثيات GPS. توجيه الإسعاف...",
        wfHospital: "تم التواصل مع المستشفى بنجاح. تجهيز الطوارئ.",
        liveBadge: "نظام توجيه الإسعاف الذكي مفعل",
        mainHeroTitle: "كل ثانية <br> <span class=\"text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-primary\">تُنقذ حياة.</span>",
        mainHeroDesc: "منصة إنقاذ تقوم بأتمتة كشف الحوادث، والتحقق منها لحظياً، وتوجيه أقرب سيارة إسعاف لإنقاذ المصابين.",
        btnTrack: "تتبع حالة المريض",
        
        simTitle: "خريطة التنسيق اللحظي",
        driver_dashboard: "لوحة تحكم الإسعاف",
sim_mode: "وضع المحاكاة",
actual_mode: "الوضع الحقيقي",
status_available: "متاح للخدمة",
status_offline: "خارج الخدمة",
waiting_missions: "في انتظار بلاغات جديدة...",
patient_info: "بيانات المصاب",
target_hospital: "المستشفى الموجه إليه",
confirm_arrival: "تأكيد الوصول لموقع الحادث",
confirm_delivery: "تأكيد تسليم الحالة",
blood_type: "فصيلة الدم",
medical_notes: "ملاحظات طبية",
impact_force: "قوة الاصطدام",
vehicle_speed: "سرعة المركبة",
car_info: "بيانات المركبة",
        searchTitle: "تتبع حالة المريض",
        searchDesc: "أدخل المعرف الفريد للجهاز (Device UID) لمعرفة الحالة اللحظية والمستشفى الموجه إليه المريض.",
        deviceUid: "معرف الجهاز (UID)",
        btnSearch: "البحث في قاعدة البيانات",
        
        howTitle: "بروتوكول النظام",
        step1Title: "اكتشاف الحادث",
        step1Desc: "مستشعرات الحركة تكتشف الاصطدام فوراً وترسل الإحداثيات.",
        step2Title: "10 ثواني للتحقق",
        step3Title: "التوجيه التلقائي",
        step4Title: "تنبيه المستشفى",
        step4Desc: "أقرب مستشفى يستلم بيانات المريض لتجهيز الطوارئ فوراً.",
        // --- Admin Global UI ---
        desktopOnly: "للكمبيوتر والتابلت فقط",
        desktopOnlyDesc: "غرفة التحكم تتطلب شاشة أكبر لعرض الخريطة والتتبع اللحظي.",
        returnHome: "العودة للرئيسية",
        adminTitle: "إدارة إنقاذ",
        aiDispatch: "توجيه ذكي نشط",
        maximizeMap: "تكبير الخريطة",
        showPanels: "إظهار القوائم",
        
        // --- Sidebar ---
        navDash: "لوحة القيادة",
        navUsers: "المستخدمين",
        navHospitals: "المستشفيات",
        navAmbulances: "الإسعافات",

        // --- Dashboard Module ---
        dashIncidents: "الحوادث",
        dashFleet: "الأسطول",
        dashDevices: "الأجهزة النشطة",
        searchDevicePlaceholder: "بحث بالمعرف أو المالك...",
        panelDetailsTitle: "التفاصيل",

        // --- Users Module ---
        usersTitle: "إدارة المستخدمين",
        usersDesc: "إدارة السائقين، المستشفيات، المديرين، ومستخدمي التطبيق.",
        addNewUser: "إضافة مستخدم",
        searchUsers: "بحث بالاسم، الإيميل، ID...",
        allRoles: "جميع الصلاحيات",
        allStatus: "جميع الحالات",
        active: "نشط",
        suspended: "موقوف",
        id: "الرقم",
        name: "الاسم",
        email: "البريد الإلكتروني",
        phone: "الهاتف",
        role: "الصلاحية",

        // --- Hospitals Module ---
        hospTitle: "شبكة المستشفيات",
        hospDesc: "إدارة المنشآت، المواقع، والسعة اللحظية للأسرة.",
        addHosp: "إضافة مستشفى",
        searchHosp: "بحث بالاسم، المدينة، ID...",
        allCapacities: "جميع السعات",
        bedsAvailable: "يوجد أسرة",
        fullBeds: "ممتلئ (0 أسرة)",
        hospName: "اسم المستشفى",
        location: "الموقع",
        availBeds: "الأسرة المتاحة",
        adminAcc: "حساب الإدارة",
// --- Devices Module ---
        navDevices: "الأجهزة النشطة",
        devTitle: "إدارة الأجهزة",
        devDesc: "إدارة وحدات رصد الحوادث، تعيين الملاك، وتتبع الحالة اللحظية.",
        addDevice: "إضافة جهاز",
        searchDevice: "بحث بالمعرف، المالك، اللوحة...",
        colDeviceUid: "المعرف (UID)",
        colOwner: "بيانات المالك",
        colCarInfo: "بيانات السيارة",
        modalAddDevTitle: "إضافة جهاز جديد",
        lblDeviceUid: "المعرف الفريد للجهاز",
        lblAssignUser: "ربط بمستخدم",
        lblCarModel: "موديل وسنة الصنع",
        lblCarPlate: "رقم اللوحة",
        btnSaveDevice: "حفظ الجهاز",
        modalViewDevTitle: "ملف الجهاز",
        lblRegDate: "تاريخ التسجيل",
        modalDevFilterTitle: "فلتر الأجهزة الجغرافي",
        lblFilterDescDev: "اضغط على الخريطة لتحديد نقطة المركز، ثم اضبط النطاق للبحث عن الأجهزة في هذا المحيط.",
        unassigned: "غير معين",
        confirmTitle: "هل أنت متأكد؟",
        confirmMessage: "هذا الإجراء لا يمكن التراجع عنه.",
        btnTraffic: "الزحام المروري",
        btnHeatmap: "الخريطة الحرارية",
        notifications: "الإشعارات الحية",
        noNotifs: "لا توجد إشعارات جديدة",
        logout: "تسجيل الخروج",
        // --- Ambulances Module ---
        ambTitle: "إدارة الأسطول",
        ambDesc: "إدارة سيارات الإسعاف، السائقين، ونقاط التمركز.",
        addAmb: "إضافة سيارة",
        searchAmb: "بحث بالكود، السائق...",
        mapFilter: "فلتر الخريطة",
        unitCode: "كود السيارة",
        assignedDriver: "السائق المعين",
        baseZone: "نقطة التمركز",
        // --- Logs Module ---
        navLogs: "سجل العمليات",
        logsTitle: "سجل نشاطات النظام",
        logsDesc: "تتبع جميع الإجراءات الإدارية، التحديثات، وعمليات الحذف.",
        searchLogs: "بحث باسم المدير، تفاصيل...",
        allActions: "كل الإجراءات",
        allTables: "كل الوحدات",
        colDate: "التاريخ والوقت",
        colAdmin: "المدير (المسؤول)",
        colAction: "الإجراء",
        colTarget: "الوحدة المستهدفة",
        colNote: "التفاصيل / ملاحظات",
        // --- Incidents Module ---
        navIncidents: "سجل الحوادث",
        incRecordsTitle: "سجلات الطوارئ والحوادث",
        incRecordsDesc: "مراجعة تاريخ الحوادث، بيانات الاصطدام، وأوقات الاستجابة.",
        searchInc: "بحث برقم الحادث، معرف الجهاز...",
        colGForce: "قوة الاصطدام",
        colResponse: "حالة الاستجابة",
        modalViewIncTitle: "تقرير الحادث التفصيلي",
        lblIncidentTime: "وقت وقوع الحادث",
        lblResolvedTime: "وقت الإغلاق",
        lblAssignedAmb: "الإسعاف الموكل",
        lblAssignedHosp: "المستشفى المستقبل",
        modalIncFilterTitle: "بحث الحوادث الجغرافي",
        lblFilterDescInc: "تحديد موقع الحوادث ضمن نطاق معين على الخريطة.",

        speed: "السرعة عند الاصطدام",
        timeline: "التسلسل الزمني للحادثة",
        outcome: "النتيجة الطبية",
        treated: "تمت المعالجة / خروج",
        deceased: "وفاة",
        impactPoint: "موقع الاصطدام",
        stepCreated: "رصد الاصطدام",
        stepAssigned: "تعيين سيارة إسعاف",
        stepArrived: "وصول الإسعاف للموقع",
        stepHospital: "الوصول للمستشفى",
        stepResolved: "إغلاق الحالة الطبية",
        sysInit: "تم تشغيل النظام. جاري فحص المنطقة...",
crashDetected: "تم رصد حادث: سيارة مدنية رقم ",
dispatching: "جاري توجيه إسعاف",
toCrashSite: "إلى موقع الحادث...",
securingPatient: "يقوم بتأمين المصاب...",
routingTo: "في طريقه إلى مستشفى",
droppedPatient: "تم تسليم الحالة. العودة للدورية.",
wfComplete: "اكتمل البروتوكول. جاري إعادة التشغيل...",
wfImpact: "تم اكتشاف اصطدام. جاري جمع البيانات...",
wfUplink: "تم الاتصال بالشبكة. جاري التحقق من الإشارة...",
wfAnalysing: "جاري تحليل إحداثيات GPS. توجيه الإسعاف...",
wfHospital: "تم التواصل مع المستشفى بنجاح. تجهيز الطوارئ.",

        // --- User Dashboard ---
        userDashTitle: "لوحة المستخدم | إنقاذ",
        userGreeting: "مرحباً",
        tabIncidents: "سجل الحوادث",
        tabVisitors: "سجل الزوار",
        tabSettings: "الإعدادات",
        incHistoryTitle: "سجل الحوادث",
        incSearchPh: "بحث برقم الحادث...",
        filterAll: "الكل",
        visitorLogsTitle: "من بحث عنك",
        visSearchPh: "بحث بالإيميل...",
        visEmail: "البريد الإلكتروني للباحث",
        visMethod: "طريقة البحث",
        visQuery: "مصطلح البحث",
        noVisitors: "لا يوجد سجل بحث عنك",
        settingsTitle: "الإعدادات الشخصية",
        personalInfo: "المعلومات الشخصية",
        medicalInfo: "المعلومات الطبية",
        allergies: "حساسية",
        medications: "أدوية",
        chronicConditions: "أمراض مزمنة",
        emergencyContacts: "جهات الاتصال الطارئة",
        ec1Name: "اسم جهة الاتصال 1",
        ec1Phone: "هاتف جهة الاتصال 1",
        ec1Relation: "العلاقة",
        changePassword: "تغيير كلمة المرور",
        updatePassword: "تحديث",
        saveAll: "حفظ جميع التغييرات",
        incReportTitle: "تقرير الحادث",

    }
};

export let currentLang = localStorage.getItem('resq_lang') || 'en';

// دالة تصدير لترجمة الكلمات داخل ملفات الـ JS
export function t(key) {
    return translations[currentLang][key] || key;
}

export function applyLanguage(lang) {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    
    // ترجمة عناصر الـ HTML الثابتة
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });

    // ترجمة الـ Placeholders
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[lang][key]) {
            el.placeholder = translations[lang][key];
        }
    });

    const langToggleBtn = document.getElementById('langToggleBtn');
    if(langToggleBtn) {
        langToggleBtn.innerHTML = translations[lang].langBtn;
    }

    // عكس اتجاه النصوص في الحقول (اختياري)
    document.querySelectorAll('input:not([type="hidden"])').forEach(input => {
        input.style.textAlign = lang === 'ar' ? 'right' : 'left';
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const langToggleBtn = document.getElementById('langToggleBtn');
    
    langToggleBtn?.addEventListener('click', () => {
        currentLang = currentLang === 'en' ? 'ar' : 'en';
        localStorage.setItem('resq_lang', currentLang);
        applyLanguage(currentLang);
        
        // إرسال حدث (Event) لباقي الملفات لتحديث الجداول والنصوص الديناميكية
        window.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang: currentLang } }));
    });

    applyLanguage(currentLang);
});