-- ============================================================================
-- 🏥 EnQaZ Hospital Dashboard - Database Migration
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- ============================================================================

-- 1. Hospital Beds Table
create table public.hospital_beds (
  id bigint generated by default as identity not null,
  hospital_id bigint not null,
  bed_number integer not null default 1,
  status character varying(20) not null default 'available',
  patient_name character varying(255) null,
  patient_id character varying(255) null,
  incident_id bigint null,
  admission_time timestamp with time zone null,
  created_at timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint hospital_beds_pkey primary key (id),
  constraint hospital_beds_hospital_id_fkey foreign key (hospital_id) references hospitals (id) on update restrict on delete cascade,
  constraint hospital_beds_incident_id_fkey foreign key (incident_id) references incidents (id) on update restrict on delete set null,
  constraint hospital_beds_status_check check (status in ('available', 'occupied', 'blocked'))
) tablespace pg_default;

create index idx_hospital_beds_hospital on public.hospital_beds using btree (hospital_id);
create index idx_hospital_beds_status on public.hospital_beds using btree (status);

-- 2. Hospital Logs Table
create table public.hospital_logs (
  id bigint generated by default as identity not null,
  hospital_id bigint not null,
  action character varying(50) not null,
  metadata jsonb null default '{}',
  created_at timestamp with time zone not null default CURRENT_TIMESTAMP,
  constraint hospital_logs_pkey primary key (id),
  constraint hospital_logs_hospital_id_fkey foreign key (hospital_id) references hospitals (id) on update restrict on delete cascade
) tablespace pg_default;

create index idx_hospital_logs_hospital on public.hospital_logs using btree (hospital_id);
create index idx_hospital_logs_action on public.hospital_logs using btree (action);
create index idx_hospital_logs_created on public.hospital_logs using btree (created_at desc);

-- 3. Enable Row Level Security (open policies for now)
alter table public.hospital_beds enable row level security;
create policy "Allow all for hospital_beds" on public.hospital_beds for all using (true) with check (true);

alter table public.hospital_logs enable row level security;
create policy "Allow all for hospital_logs" on public.hospital_logs for all using (true) with check (true);

-- 4. Enable Realtime
alter publication supabase_realtime add table hospital_beds;
alter publication supabase_realtime add table hospital_logs;
